apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::766386820142:user/stick.verse
      username: stick.verse
      groups:
        - system:masters
