// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: maplist.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GridId uint64 `protobuf:"varint,1,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
}

func (x *TableRequest) Reset() {
	*x = TableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maplist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRequest) ProtoMessage() {}

func (x *TableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maplist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRequest.ProtoReflect.Descriptor instead.
func (*TableRequest) Descriptor() ([]byte, []int) {
	return file_maplist_proto_rawDescGZIP(), []int{0}
}

func (x *TableRequest) GetGridId() uint64 {
	if x != nil {
		return x.GridId
	}
	return 0
}

type TableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GridId    uint64      `protobuf:"varint,1,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
	Grid      *Grid       `protobuf:"bytes,3,opt,name=grid,proto3" json:"grid,omitempty"`
	Locations []*Location `protobuf:"bytes,7,rep,name=locations,proto3" json:"locations,omitempty"`
}

func (x *TableResponse) Reset() {
	*x = TableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maplist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableResponse) ProtoMessage() {}

func (x *TableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maplist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableResponse.ProtoReflect.Descriptor instead.
func (*TableResponse) Descriptor() ([]byte, []int) {
	return file_maplist_proto_rawDescGZIP(), []int{1}
}

func (x *TableResponse) GetGridId() uint64 {
	if x != nil {
		return x.GridId
	}
	return 0
}

func (x *TableResponse) GetGrid() *Grid {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *TableResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type LibraryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinX int64 `protobuf:"varint,1,opt,name=minX,proto3" json:"minX,omitempty"`
	MaxX int64 `protobuf:"varint,2,opt,name=maxX,proto3" json:"maxX,omitempty"`
	MinY int64 `protobuf:"varint,3,opt,name=minY,proto3" json:"minY,omitempty"`
	MaxY int64 `protobuf:"varint,4,opt,name=maxY,proto3" json:"maxY,omitempty"`
}

func (x *LibraryRequest) Reset() {
	*x = LibraryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maplist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryRequest) ProtoMessage() {}

func (x *LibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maplist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryRequest.ProtoReflect.Descriptor instead.
func (*LibraryRequest) Descriptor() ([]byte, []int) {
	return file_maplist_proto_rawDescGZIP(), []int{2}
}

func (x *LibraryRequest) GetMinX() int64 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *LibraryRequest) GetMaxX() int64 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *LibraryRequest) GetMinY() int64 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *LibraryRequest) GetMaxY() int64 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type LibraryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grids []*Grid `protobuf:"bytes,7,rep,name=grids,proto3" json:"grids,omitempty"`
}

func (x *LibraryResponse) Reset() {
	*x = LibraryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maplist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryResponse) ProtoMessage() {}

func (x *LibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maplist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryResponse.ProtoReflect.Descriptor instead.
func (*LibraryResponse) Descriptor() ([]byte, []int) {
	return file_maplist_proto_rawDescGZIP(), []int{3}
}

func (x *LibraryResponse) GetGrids() []*Grid {
	if x != nil {
		return x.Grids
	}
	return nil
}

var File_maplist_proto protoreflect.FileDescriptor

var file_maplist_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x27, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x67, 0x72, 0x69, 0x64, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x0d, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x72, 0x69,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x67, 0x72, 0x69, 0x64,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x67, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x69, 0x64, 0x52, 0x04, 0x67, 0x72, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x60, 0x0a, 0x0e,
	0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x69,
	0x6e, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x78, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6d, 0x61, 0x78, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x59, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61,
	0x78, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x61, 0x78, 0x59, 0x22, 0x31,
	0x0a, 0x0f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x05, 0x67, 0x72, 0x69, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x69, 0x64, 0x52, 0x05, 0x67, 0x72, 0x69, 0x64,
	0x73, 0x32, 0xa0, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x06, 0x2f,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x22, 0x08, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x3a, 0x01, 0x2a, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maplist_proto_rawDescOnce sync.Once
	file_maplist_proto_rawDescData = file_maplist_proto_rawDesc
)

func file_maplist_proto_rawDescGZIP() []byte {
	file_maplist_proto_rawDescOnce.Do(func() {
		file_maplist_proto_rawDescData = protoimpl.X.CompressGZIP(file_maplist_proto_rawDescData)
	})
	return file_maplist_proto_rawDescData
}

var file_maplist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_maplist_proto_goTypes = []interface{}{
	(*TableRequest)(nil),    // 0: pb.TableRequest
	(*TableResponse)(nil),   // 1: pb.TableResponse
	(*LibraryRequest)(nil),  // 2: pb.LibraryRequest
	(*LibraryResponse)(nil), // 3: pb.LibraryResponse
	(*Grid)(nil),            // 4: pb.Grid
	(*Location)(nil),        // 5: pb.Location
}
var file_maplist_proto_depIdxs = []int32{
	4, // 0: pb.TableResponse.grid:type_name -> pb.Grid
	5, // 1: pb.TableResponse.locations:type_name -> pb.Location
	4, // 2: pb.LibraryResponse.grids:type_name -> pb.Grid
	0, // 3: pb.MaplistService.GetTable:input_type -> pb.TableRequest
	2, // 4: pb.MaplistService.GetLibrary:input_type -> pb.LibraryRequest
	1, // 5: pb.MaplistService.GetTable:output_type -> pb.TableResponse
	3, // 6: pb.MaplistService.GetLibrary:output_type -> pb.LibraryResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_maplist_proto_init() }
func file_maplist_proto_init() {
	if File_maplist_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_maplist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maplist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maplist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LibraryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maplist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LibraryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maplist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maplist_proto_goTypes,
		DependencyIndexes: file_maplist_proto_depIdxs,
		MessageInfos:      file_maplist_proto_msgTypes,
	}.Build()
	File_maplist_proto = out.File
	file_maplist_proto_rawDesc = nil
	file_maplist_proto_goTypes = nil
	file_maplist_proto_depIdxs = nil
}
